#!/usr/bin/env ruby
# -*- coding: utf-8 -*-
# -*- ruby -*-
#

require 'rubygems'
require 'rss'
require 'open-uri'
require 'hpricot'

#
# 取得したフィードを配列で返す。
# フィードが無い場合は空配列を返す。
# 指定したURLが無効な場合はnilを返す。
#

def process_rss(rss,list)
  content = ''
  open(rss){ |f|
    content = f.read
  }
      
  rss = nil
  begin
    rss = RSS::Parser::parse(content)
  rescue RSS::InvalidRSSError
    rss = RSS::Parser::parse(content,false)
  end
  if rss then
    rss.items.each { |u|
      next if u.title =~ /^PR:/ ||
      u.title =~ /^【PR】/ ||
      u.title =~ /^【広告特集】/ ||
      u.title =~ /^AD:/ ||
      u.title =~ /^\s*$/
      list << "url:#{u.link}\ttitle:#{u.title}"
    }
  else
    content.each_with_index { |line,i|
      while line.sub!(/<link>([^<]*)<\/link>/,'') do
        list << "url:#{$1}\t記事#{i}"
      end
      while line.sub!(/<link.*href="(.*?)"/,'') do
        list << "url:#{$1}\t記事#{i}"
      end
    }
  end
end

def feeds(url)
  list = []
  begin
    server = open(url)
  rescue
    return nil
  end
  links = Hpricot(server).search('link')
  links.each { |link|
    if link.attributes['type'] == 'application/rss+xml' ||
        link.attributes['type'] == 'application/atom+xml' then
      rss = link.attributes['href']
      if rss !~ /^http:/ then
        if rss =~ /^\// then
          url =~ /(http:\/\/[^\/]+)\//
          rss = $1 + '/' + rss.sub(/^\//,'')
        else
          url.sub(/\/$/,'')
          rss = url + '/' + rss.sub(/^\.\//,'')
        end
      end

      process_rss(rss,list)

      break
    end
  }
  return list
end

def getrss(title,url)
  list = []
  process_rss(url,list)
  puts " title:#{title}"
  if list then
    list.each { |entry|
      puts "  #{entry}"
    }
  end
end

puts "title:Scrapbox"
getrss('Shokai','https://scrapbox.io/api/feed/shokai')
